# Preface {.unnumbered}

## Motivation

During my work as a junior doctor in a general practice in Gellerup, a deprived suburb of Aarhus with a large migrant population, I was immediately struck by the high frequency of type 2 diabetes (T2D) and other chronic diseases among day-to-day consultations. I would quickly learn that T2D held more surprises for me than just a high prevalence, and after just a few weeks it seemed that much of what I had learned about the disease in medical school and studied in clinical guidelines did not apply in my new setting. Patients were not only more prevalent, they were also much younger, and hemoglobin-A1c (HbA1c) levels rarely came close to guideline targets despite our best efforts to intensify treatment. Sadly, these experiences would repeat themselves in my subsequent work with migrants as a general practitioner (GP) in health clinics of the Danish Red Cross at asylum residence centers and pre-removal detention centers.

As I reviewed the literature, I understood why medical school and guidelines had failed to prepare me for the challenges I faced as a clinician with T2D in migrants: the existing literature was inadequate. While increased prevalence of T2D appeared well-established, and migrants with T2D were also ascribed a higher mortality than their native counterparts, this provided little guidance for my day-to-day work. Contrarily, there was hardly any evidence on disparities in the time between diagnosis and death - the time when care from the GP is needed the most. So I was left to wonder what might cause this discordance between what I knew about T2D from books and guidelines, and what I encountered in migrants in the clinic.\
*Are migrants with T2D more prone to under-treatment, and in which areas of care?\
Are some migrant groups more prone to under-treatment than others?\
Are their needs for T2D care simply greater?*\
Knowledge on these clinical questions would enable GPs and healthcare planners to address disparities and improve care in migrants by prioritizing and focusing care accordingly. Migrants are currently a younger demographic than the rest of the population, but as time causes the migrant demographic to age, it is likely that migrants will constitute an increasing proportion of the T2D population in the coming years. Therefore, I was excited to explore these urgent clinical questions as a researcher, hoping I could provide answers to myself and fellow GPs that could lead to better care - and, ultimately, better health - in a vulnerable and challenging group of patients.

During my time as a PhD student, I quickly encountered the first of many challenges on the way to studying migrants with T2D in the Danish registers: there was no validated definition of T2D, nor a common consensus among researchers. This led to the PhD project expanding its scope to develop and validate a tool to define T2D in the Danish registers, which allowed me to answer my research questions based on robust findings. This PhD project benefited greatly from open-source tools, and in the spirit of open science, the source code of the validated diabetes classifier was made available to other researchers in the *osdc* package for the *R* statistical programming language. As a final commitment to openness, this dissertation was made available to a global audience in website format at [aastedet.github.io/dissertation](https://aastedet.github.io/dissertation/docs/index.html)

## Outline of the dissertation

**Chapter 1** introduces the reader to diabetes and identification of diabetes patients in Danish healthcare registers, describes the clinical guidelines for T2D care in Denmark as they relate to this PhD study, and provides an outline of T2D in migrants.

**Chapter 2** states the overall aims of this PhD project and each individual study.

**Chapter 3** describes the setting, data sources, methods and study designs used in the studies of this PhD project.

**Chapter 4** presents the main results of the studies.

**Chapter 5** contains a discussion of the methods used and their potential impact on results.

**Chapter 6** discusses the findings in light of the methods used.

**Chapter 7** presents the main conclusions and their clinical implications.

**Chapter 8** draws up future perspectives of the PhD study and research field.

\newpage

## Papers associated with the dissertation

**Coming soon**

```{=tex}
\newpage

{\let\clearpage\relax \tableofcontents} 
```
