# Aims {#sec-aims}

## Overall aims

The overall aim of this PhD dissertation is to provide robust knowledge on specific areas of T2D care where disparities between migrant groups and native Danes may be present.

## Specific aims

I.  To develop a register-based classification of type 1 and type 2 diabetes that incorporates previous recommendations on data sources, and to make it available to other researchers.

II. To validate register-based diabetes classifiers available to researchers in Denmark.

III. To assess the prevalence of T2D in migrant minorities of Denmark, and to explore care disparities between migrant groups and native Danes in terms of monitoring, biomarker control and pharmacological treatment as recommended in the guidelines.

IV. To evaluate disparities in the quality of glucose-lowering pharmacological treatment between migrants and native Danes in terms of combination therapy and drug types.

## Outputs

Aim I was pursued in the creation of the *Open-Source Diabetes Classifier* (OSDC), made available in the open-source *R* package *osdc*.[@osdc] Aims II, III, and IV were pursued in the respective papers I, II, and III of this dissertation.
