# Results in summary {#sec-results}

*\[Align structure with each individual study? Or split into themes? Kind of doing both for now\]*

## Exploratory results during development of diabetes classifiers

Insulin non-users among T1D -\> Women with diabetes onset before 1997.

Self-reported no diabetes (or previous diabetes)

Insufficient obstetric coding practices before 1997.

Arguments for and against design choices goes into discussion chapter

*\[detailed discussion of choices in OSDC, e.g. on obstetric coding, and pros/cons of RSCD goes in chapter 5\]*

## Study I

In this study, we identified... Number of participants, diabetes cases etc.

### Register-based classification of type 1 diabetes

metrics

### Register-based classification of type 2 diabetes

metrics

## Study II

\[Maybe for each outcome?\] In this study, we identified... Number of participants, diabetes cases etc.

### Prevalence

### Monitoring

### Biomarker control

### Pharmacological treatment

### 

## Study III

In this study, we identified... Number of participants, diabetes cases etc.

### Combination therapy

### Drug types
