# Discussion of results {#sec-discussion-results}

## Key main findings

This dissertation identified several important findings in the three studies.
First, study I determined whether register-based classifiers can identify valid populations of T1D and T2D in a general Danish population. Second, disparities in T2D care between migrants and native Danes were investigated in two cross-sectional studies. Study II analysed T2D prevalence and disparity in care quality as outlined in guideline recommendations for monitoring, biomarker levels and pharmacological treatment, while study III explored disparities in GLD treatment in terms of combination therapy and types of GLD used.

In this chapter, the main findings of each study are discussed separately and compared to existing literature before clinical implications of the results of studies II and III are discussed. Risk factors in T2D care beyond migrant origin are of great importance in a broader scope of equity in T2D care provision. However, they are not the focus of this dissertation and are only briefly discussed as they relate to migrants.

## Study I

This study validated two predefined algorithms (the OSDC and the RSCD), which classified diabetes type in Danish register data against self-reported diabetes type in a Danish survey population. Overall, both classifiers performed excellent in terms of PPV in both T1D and T2D as well as sensitivity in T2D classification (all estimates 0.875 and above), and they had near-perfect accuracy in terms of specificity and NPV in both T1D and T2D (all estimates 0.989 and above). Both classifiers were unable to accurately classify diabetes type in individuals with T1D onset after age 40 years and T2D onset before age 40 years.

Sensitivity and NPV were higher in the OSDC than in the RSCD for both diabetes types. In T1D classification, these differences are attributable to differences in the algorithms, as both algorithms relied on the same data sources for identifying T1D (GLD use and type-specific diabetes diagnoses).[@ruks1doc] In T2D, this difference may be explained by the use of HbA1c data in the OSDC, which enables inclusion of diabetes cases at the time of diagnosis rather than requiring subsequent initiation of GLD treatment or hospitalisation. Specificity and PPV in T2D classification were higher in the RSCD than in the OSCD. This could possibly be explained by inclusion of milder cases in the latter, as this population may be less likely to correctly report having diabetes (e.g. if an individual had never purchased GLD or been hospitalised for the disease). Notably, the demographic characteristics of the register-classified diabetes populations differed, particularly in T1D, where the higher sensitivity of the OSDC in women (0.846 vs. 0.725 in supplementary analyses) resulted in a higher prevalence of women in the OSDC population compared to the RSCD population. This is in line with a previous study comparing the Danish National Diabetes Register (which did not use HbA1c) against a local database containing HbA1c as an alternative inclusion criterion, which found higher prevalences of diabetes in the HbA1c-augmented definition, especially among women.[@RN165]

To the best of my knowledge, this study was the first to validate the performance of a type-specific diabetes classifier in a general population of individuals with and without diabetes. Other studies have validated type-specific diabetes classifier performance in populations consisting only of individuals with diabetes, which fails to test the ability of the algorithm to distinguish individuals with diabetes from those without. This overestimates the accuracy of the algorithm compared to its performance in a general population. In addition, both algorithms were pre-specified, as opposed to the data-driven, exploratory approaches used in other validation studies to design algorithms optimized for a particular dataset, which holds a risk of overfitting the algorithm to the dataset and reducing the external validity of findings.[@RN174; @RN179; @RN177] Despite these differences, the performance of both our classifiers was superior to the performance of T1D classification reported in studies in the United States and Hong Kong,[@RN174; @RN178] and comparable to that reported in the United Kingdom,[@RN172] but inferior to that reported in a study in Canada.[@RN177]

The poor performance of the register-based classifiers in subgroups with diabetes onset at atypical age is likely to reflect clinical uncertainty in these cases. This may result in inaccurate type-specific diabetes diagnoses and uncharacteristic GLD purchase patterns,[@RN173] which may lead the algorithms to misclassify these individuals. Sensitivity in T1D classification has previously been reported to be highly dependent on age at onset,[@RN179] and our findings indicate that this issue also extends to PPV and to T2D classification.

## Study II

This study analysed the prevalence of T2D and disparities
between migrant groups and native Danes across eleven indicators of
guideline recommendations on monitoring, biomarker levels and
pharmacological treatment.

The prevalence of T2D was found to be higher in migrants compared to
native Danes, especially in migrants from Sri Lanka and Pakistan, who
were four to five times more likely to have T2D compared to native
Danes. While similar findings have previously been reported in Denmark
[@andersen2016; @Kristensen2007] and across Europe,[@meeks2016] our study shows that this risk
persists after adjusting for differences in socioeconomic position.

Failure to fulfil guideline recommendations and targets for T2D care was common. The proportion of native Danes unable to fulfil recommendations was below
10\% in only two indicators (HbA1c-monitoring and GLD-treatment) and
above 25\% in eight (all remaining indicators excluding LDL-C monitoring).
Non-fulfilment of guideline recommendations was more common in migrants, particularly in terms of monitoring and controlling HbA1c and LDL-C levels. In most of these
indicators, we observed increased crude risks at a significance level of
$\alpha = 0.05$ in most migrant groups, whereas no clear overall pattern was observed across migrant groups in the indicators of pharmacological treatment.

The disparity between migrants and native Danes was
largest in the indicators of glycaemic control and screening for diabetic
foot disease (crude risk was increased by more than one-third in
most migrant groups). Migrants from Somalia stood out across all aspects of T2D care. The group had increased crude risk in all eleven indicators, and the highest risk of all migrants in nine. In addition, the largest single disparity was observed in migrants from Somalia, who had almost twice the crude risk of native Danes in the indicator of lipid control.

Our findings of lower likelihood of T2D monitoring in most migrant
groups contrast the findings in prior studies, where migrants received
similar or more monitoring compared to native Danes,[@Kristensen2007] 
Norwegians[@Tran2010] and Swedes.[@Rawshani2015] Still, it is in line with recent findings of less timely monitoring in ethnic minority groups in England.[@Whyte2019] The proportion of the T2D population without timely monitoring varied substantially
between each type of monitoring, but socioeconomic factors such as household
income and region of residence were risk factors in all types of
monitoring. Screening for diabetic foot disease is the only service
that is not fully covered by the public health
insurance in Denmark (requiring the patient to pay a fee), which may explain why this indicator had the highest
proportion of individuals without timely monitoring. In addition, the large disparity
between migrants and native Danes in this indicator, which persisted
after adjusting for socioeconomic variables, suggests that economic
barriers may disproportionately limit the access to care in migrant groups.

In line with previous studies, most migrant groups were less likely than
native Danes to achieve glycaemic control.[@Tran2010; @Negandhi2013, @Rawshani2015; @Whyte2019] The magnitude of the
risk was similar to what has previously been reported, although
it may seem lower compared to estimates reported as ORs in other studies, since ORs may lead to exaggerated risk estimates if
interpreted as RR when the outcome is common.[@holcomb2001] For example, a study in
Scotland reported a crude OR of dysglycaemia of 2.2 in the Pakistani
group and a dysglycaemia-prevalence of roughly 50\% in the reference
group;[@Negandhi2013] this corresponds to an RR of 1.4,[@Grant2014] which is similar to our
estimate.

To the best of my knowledge, increased LDL-C levels among migrants have not previously been reported,[@Eastwood2021] although a small US study noted a minor trend towards higher lipid levels in migrants from Somalia.[@Wieland2012] Three studies have examined obesity in migrants from Somalia and found high prevalences of obesity and increased waist-to-hip ratio in women, but not in
men. [@Gele2013; @Skogberg2018; @Ahmed2018] If this pattern between sexes extends to migrants from Somalia in Denmark, it seems unlikely that anthropometric factors alone can
explain the high levels of LDL-C in this population, as the risk
remained unchanged in supplementary analyses stratified by sex (not included in this dissertation).

Most studies of pharmacological treatment in T2D have analysed the whole
population (rather than analysing groups with a clinical indication for
treatment) and have evaluated incident medication use in cohorts of
newly diagnosed, making direct comparisons to our findings difficult.
The finding of lower or similar risk of GLD non-use in most migrant
groups is in line with previous studies comparing migrants to native
populations. [@Tran2010; @Rawshani2015] However, the lower risk of LLD non-use in most migrant groups contrasts findings from prior studies.[@RamirezSanchez2013; @Tran2010; @Eastwood2021] The increased risk of dysglycaemia in the Somalia group coincided with an
increased risk of not receiving GLD. This pattern was also observed
for dyslipidaemia and LLD non-use in the Somalia and Europe groups, indicating a
particular need to the increase uptake of pharmacological treatment in these
groups.
Similar to a study from Italy, we found a higher risk of not receiving ACEI/ARB treatment in most migrant groups. In contrast, the risk of not receiving APT was similar in most groups in our study.[@Marzona2018] As the indications for treatment with ACEI/ARB and APT were identical in our study, one might expect similar risk patterns in these outcomes. Yet, this was not the case, which might be due to unmeasured differences between the groups in terms of indications, counter-indications,
awareness of and attitude to these drugs.

Some of the disparities between migrants and native Danes could be
attributed to a higher prevalence of risk factors of poor T2D care
in migrants; specifically young age, low household income and residence
in the Capital Region of Denmark.

## Study III

This study explored disparities in GLD treatment in terms of combination therapy and types of GLD used, adding to the analysis of the indicator of GLD treatment performed in study II. The analysis of GLD in study II found no overall pattern of disparity across migrant groups, but it did not capture nuances in the treatment provided, because the analysis was a simple evaluation of any GLD treatment being present or not. In this study, most migrant groups were found to be less likely to receive combination GLD therapy than native Danes. We also found that, compared to native Danes, most migrant groups were more likely to receive oral GLD types (metformin, sulfonylureas, DPP4i, and SGLT2i) and less likely to receive injection-based GLD types (insulins and GLP1RA). Disparity was largest in GLP1RA use, where the RR ranged from 0.30 to 0.60 in most migrant groups.

As in study II, migrants from Somalia stood out; they had the lowest likelihood of receiving combination therapy and GLP1RA of all groups.

To the best of my knowledge, combination therapy usage has not previously been studied in migrants. Still, disparities between racial groups have been examined, and these proxies of ethnicity provide a basis for comparisons. With the notable exception of migrants in the four smallest migrant groups (Pakistan, Sri Lanka, Somalia and Vietnam), the migrants in our study received combination therapy on a level close to native Danes after adjustments (RRs around 0.95 to 1.05). Since combination therapy is not a hard clinical endpoint, we argue that the modest disparities observed in the largest groups of migrants (covering more than three-quarters of the total migrant T2D population) were insignificant from a clinical perspective. At a glance, this may contrast another UK study reporting a high odds ratio of experiencing inertia in initiation of combination therapy in non-white groups compared to Whites (e.g. odds ratio in Blacks: 1.43) and reporting their findings as persuasive evidence of disparities.[@RN226] However, the high prevalence of inertia in the reference group (67.1%) of the study exaggerates this risk estimate if interpreted as RR, and the corresponding RR (around 1.11 in Blacks)[@Grant2014] is more in line with our findings.

The higher prevalence of metformin, sulfonylurea and DPP4i in migrant groups is in line with previous reports in non-white minorities.[@Whyte2019; @RN225] The particularly high prevalence of sulfonylureas in migrants from Vietnam may reflect care being influenced by practice in the origin country, as sulfonylureas are  used in roughly three quarters of all T2D patients in Vietnam.[@RN238] In contrast, the higher prevalence of SGLT2 found in our study contradicts previous studies on racial minorities.[@RN225; @RN222; @RN219]
The very low prevalence of GLP1RA use in migrants compared to the native population has not previously been reported, but is in line with previous reports of disparities in non-white minorities.[@Whyte2019; @RN225; @RN222] Similarly, the low prevalence of insulin treatment in migrants with T2D is consistent with an Italian study[@Marchesini2014] and studies on non-white minorities elsewhere.[@Whyte2019; @RN236]

The main analyses were limited to GLD use in 2019, as we only had access to data on co-variables in the time before 2019. GLD treatment practice changed considerably in the subsequent years (even before the broadening of GLP1RA/SGLT2i-recommendations in 2022), and our findings may not persist in the new clinical context. However, supplementary analyses of GLD use in 2021 found that, despite substantial changes to GLD use compared to 2019, including >50% increases in GLP1RA and SGLT2i user-prevalences, disparities between migrants and native Danes remained unchanged. This may indicate that our findings are robust rather than limited to a clinical setting of narrow indication or low prevalence of use of these drugs.

## Clinical implications

In study II, the evaluation of quality of care using binary process and outcome indicators does not capture qualitative differences in the provided care, nor does it account for
valid patient-specific reasons for not providing care or achieving
biomarker control. In some individuals, failure to achieve biomarker
control may be unrelated to the quality of provided care (e.g. due to
genetic factors), and a lack of monitoring may not affect risk factors
and the risk of adverse outcomes. In contrast, there is less leeway for the timely provision of pharmacological treatment to patients with a guideline indication for treatment. Drug side-effects or contra-indications may be valid clinical reasons for a patient to not receive a particular drug. However, this is likely to only explain a very small fraction of non-users, as it is unlikely that these reasons prohibit all treatment options offered by guidelines (e.g. all types of GLD or LLD). Thus, relative to monitoring and biomarker levels, the clinical implications of disparities in pharmacological treatment are clearer, and they require further discussion below.

Barriers to pharmacological treatment may originate from the healthcare system, the clinician, and the patient. Therefore, efforts to increase the use should  target these.

Healthcare policies affecting patient-incurred costs are major determinants of pharmacological treatment accessibility. [@RN231; @RN232] In the Danish universal healthcare system, the annual drug expenditures are partially covered from €132 and fully covered from €553 (2019 limits). While patients with higher medication expenses will incur similar costs, regardless of the number or types of GLD used, patients treated with fewer, less expensive drugs will receive only limited coverage, and they may perceive costs as a barrier to using the newer, more expensive GLD types. In study III there were indications of financial barriers to using the more expensive GLD regimens, as lower household income was associated with less use of triple combination therapy, SGLT2i and GLP1RA (see supplementary material). This could indicate that broader coverage of GLD expenditures may serve to increase the use of combination therapy, SGLT2i and GLP1RA in the poorest patient groups, in which migrants constitute a disproportionately large share.

Clinicians may be reluctant to prescribe insulin in migrants if a language barrier is present, given the complex nature of administrations and the risk of hypoglycaemia. However, the use of GLP1RA does not carry these risks and should not take up more resources of the prescriber (e.g. physician or staff consultation time) over oral GLD, even if language barriers are present. Increasing GP awareness of disparities in pharmacological treatment of migrants with T2D (e.g. by increasing focus on migrants in clinical guidelines) may reduce the risk of suboptimal pharmacological treatment in these groups.

Patient preference of oral administration over injection-based drugs is also likely to influence prescribing. Migrant origin may influence this preference, which could explain the divergent findings between oral and injection drugs, particularly between GLP1RA and SGLT2i. Other studies have reported several reasons for insulin-aversion among migrants, including fears of weight gain, loss of independence, risk of hypoglycemia and death.[@RN233; @RN234; @RN239] Similar fears may be present for GLP1RA use in migrants due to the administration similarities to insulin injections, and patient education may be able to address these.

The massive disparities faced by migrants from Somalia in all areas of care studied in this PhD project hold particular implications for clinicians (and perhaps also for health planners and local communities). Overall, they indicate that clinicians treating patients in this group should consider close attention to care quality in this group, particularly in relation to pharmacological treatment with GLDs and LLDs. Specifically, LLDs are available in relatively inexpensive oral form, and expenditures and patient preference seem less likely to be major barriers to use of these drugs. Therefore, increasing awareness among GPs to the high lipid levels and need for LLD treatment in patients from Somalia with T2D may be a potential approach to increase treatment quality and reduce complication risk in this group.