# Conclusions {#sec-conclusion}

## Main conclusions

Five main conclusions can be derived from this dissertation.

First, both of the register-based diabetes classifiers identified valid populations of T1D and T2D in a general Danish population, with substantially higher sensitivity in the OSDC compared to the RSCD. Neither of the two algorithms was able to accurately classify diabetes type in individuals with T1D onset after age 40 years, nor T2D onset before age 40 years, and results from register-based studies of these groups should be interpreted with caution.

Second, compared to native Danes, the prevalence of T2D was higher in most migrant groups, the quality of monitoring was inferior, and most migrant groups had higher risks of not achieving glycaemic and lipid control, despite similar prevalence of pharmacological treatment.

Third, most migrant groups were less likely than native Danes to use combination GLD therapy, and migrants were more likely to use oral GLDs and less likely to use injection-based GLDs, particularly GLP1RA.

Fourth, T2D care was poorest in migrants from Somalia, who had higher risk than native Danes in all eleven guideline indicators assessed, and they also had the lowest likelihood of using combination therapy and GLP1RA of all groups. Their almost double risk of dyslipidaemia combined with a higher risk of LLD non-use compared to native Danes appeared to be an area of care with a particular potential for improvement to reduce complication risk.

Finally, clinicians treating migrants with T2D should be aware of the the most substantial disparities in T2D care within each migrant group. These are summarised in the table below, which highlights the areas of T2D care, where disparities relative to native Danes are greater than 10%.

::: {#tbl-groups layout-ncol="1"}
+-------------------+-----------------+-----------------------+-------------------------------+
| **Migrant group** | **Monitoring**  | **Biomarker control** | **Pharmacological treatment** |
+===================+=================+=======================+===============================+
| **Middle East**   | Nephropathy     | HbA1c                 | GLD                           |
|                   |                 |                       |                               |
|                   | Retinopathy     |                       | **ACEI/ARB**                  |
|                   |                 |                       |                               |
|                   | **Podiatrist**  |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Europe**        | **HbA1c**       | LDL-C                 | **GLD**                       |
|                   |                 |                       |                               |
|                   | LDL-C           |                       |                               |
|                   |                 |                       |                               |
|                   | Nephropathy     |                       |                               |
|                   |                 |                       |                               |
|                   | Retinopathy     |                       |                               |
|                   |                 |                       |                               |
|                   | Podiatrist      |                       |                               |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Turkey**        | **Podiatrist**  | HbA1c                 | **ACEI/ARB**                  |
|                   |                 |                       |                               |
|                   |                 |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+
| **F. Yugoslavia** | Retinopathy     | HbA1c                 | **GLP1RA**                    |
|                   |                 |                       |                               |
|                   | **Podiatrist**  |                       |                               |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Pakistan**      | Nephropathy     | HbA1c                 | **GLD**                       |
|                   |                 |                       |                               |
|                   | **Retinopathy** |                       | **ACEI/ARB**                  |
|                   |                 |                       |                               |
|                   | **Podiatrist**  |                       | Combination therapy           |
|                   |                 |                       |                               |
|                   |                 |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Sri Lanka**     | None \>1.10     | None \>1.10           | **ACEI/ARB**                  |
|                   |                 |                       |                               |
|                   |                 |                       | **Combination therapy**       |
|                   |                 |                       |                               |
|                   |                 |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Somalia**       | **Nephropathy** | HbA1c                 | **GLD**                       |
|                   |                 |                       |                               |
|                   | Retinopathy     | **LDL-C**             | LLD                           |
|                   |                 |                       |                               |
|                   | **Podiatrist**  |                       | **ACEI/ARB**                  |
|                   |                 |                       |                               |
|                   |                 |                       | **APT**                       |
|                   |                 |                       |                               |
|                   |                 |                       | **Combination therapy**       |
|                   |                 |                       |                               |
|                   |                 |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+
| **Vietnam**       | **HbA1c**       | None \>1.10           | **Combination therapy**       |
|                   |                 |                       |                               |
|                   | **Podiatrist**  |                       | **GLP1RA**                    |
+-------------------+-----------------+-----------------------+-------------------------------+

Notes

-   Based on estimates of relative risk in studies II and III adjusted for differences in clinical risk factors (model 1).
-   Disparities less than 10% compared to native Danes are not shown.
-   Disparities greater than 20% are highlighted in **bold**.
-   Abbreviations: HbA1c: haemoglobin-A1C. LDL-C: Low-density lipoprotein cholesterol. ACEI/ARB: Angiotensin-converting enzyme-inhibitors or angiotensin receptor blockers. GLP1RA: Glucagon-like peptide-1 receptor agonists.

**Highlights of disparities within each migrant group**
:::
