# Perspectives and future research {#sec-perspectives}

## Perspectives

Based on the findings of this dissertation, diabetes epidemiologists can rely on OSDC and RSCD to provide valid study populations of T1D and T2D for Danish register-based research, and the validated, open-source classifiers provide robust and transparent tools for researchers using these data. In addition, the findings indicate that other register-based diabetes definitions based on Danish register data from similar time-periods with comparable algorithm designs are likely to be provide valid T1D and T2D populations as well. Some caveats remain, however, as register-classified diabetes type in cases with atypical age at onset of diabetes should be interpreted with caution, and the onset of diabetes may not be accurately captured by the classifiers.

Migrants are an increasingly important part of the T2D population due to their high T2D prevalence, which will continue to rise in the future as their demography ages. Accordingly, addressing the particular care needs of migrants with T2D is going to become an increasingly pressing matter to clinicians and healthcare planners, if all individuals with T2D are to receive appropriate care. This dissertation answered an easy part of this challenge, the *what*: what are the disparities in care quality faced by migrants? The hard part is to answer the *why*: why is it harder to deliver adequate care in migrants? - and ultimately, the *how*: how can healthcare resources be prioritized to provide adequate T2D care to those with the greatest needs?

Migrant origin is a complex entity, T2D is a complex disease with several care modalities, and in combination they are a formidable challenge to clinicians and researchers. Without more supporting knowledge on the causes of care disparities or how to effectively address them in migrants with T2D, our findings alone are insufficient to guide healthcare planners or sway clinical practice.

## Future research

In register-based classification of diabetes, discerning T1D from T2D using insulin vs. non-insulin GLD purchases is likely to become a greater challenge in the future, as SGLT2i and GLP1RA may establish themselves as treatment options in T1D due to their effects on cardiovascular and kidney risk. In addition, as these GLD types are increasingly used in heart and kidney patients without diabetes, and inclusion criteria in register-based algorithms will have to adapt accordingly. In light of these changes, further validation studies are needed in order to ensure robust classifications in the future.

Disparities in diabetes care in migrants should be studied further, particularly the causes of disparities, how they affect complication risk, and how interventions can be designed to effectively reduce complication risk in migrant patients. Due to the differences in healthcare delivery and migrant group composition between countries, studies from several countries are needed to provide knowledge on as many migrant groups and healthcare system contexts as possible. Disparities in monitoring, biomarker levels, and pharmacological treatment of T2D are likely the result of underlying cultural and lifestyle factors in migrants that are poorly understood. A better understanding of these factors is needed to design interventions that can effectively address migrants and their challenges in a culturally appropriate and patient-centered way. Thus, future research should not be limited to traditional, clinical aspects of T2D care surrounding these disparities, but some questions are particularly relevant to this dissertation. Beyond combination therapy and drug type, several factors contribute to optimal pharmacological treatment, but have yet to be examined. Factors such as daily dosage of each GLD and adherence to medication may hold potential for improving risk profiles in patients with T2D, and sub-optimal care in these factors could also be more common in migrants than native Danes, if the observed disparities in other aspects of care are a general indication. Furthermore, while there is no evidence to the contrary, it is not clear if HbA1c, LDL-C, and GLP1RA have the same impact on complication risk in migrants as in the (predominantly) white, native European populations in which their effects have mainly been studied. In order to prioritize future interventions and best inform intervention design, future studies are needed to assess the risk-modifying effects of these disparities, as well as their causes. Finally, the poor level of care in migrants from Somalia in Denmark is striking, and merits further studies in other countries with large Somali minorities to assess if these findings are applicable in a broader, international context.
