project:
  type: book
  output-dir: docs
  
book:
  title: "Type 2 diabetes in migrants: register-based analyses"
  author: "Anders Aasted Isaksen"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - 0-disclosure.qmd
    - 0-preface.qmd
    - 0-abbreviations.qmd
    - 1-introduction.qmd
    - 2-aims.qmd
    - 3-methods.qmd
    - 4-results.qmd
    - 5-discussion-methods.qmd
    - 6-discussion-results.qmd
    - 7-conclusions.qmd
    - 8-perspectives.qmd
    - references.qmd
    - summary-english.qmd
    - summary-danish.qmd
  appendices:
    - app1-papers.qmd
    - app2-supplementary.qmd

citation:
  url: https://aastedet.github.io/dissertation/
bibliography: references.bib
csl: citestyle.csl

execute:
  freeze: auto
  echo: false # change to false to hide code
  

format:
  html:
    theme: cosmo
    default-image-extension: svg
  docx: 
    toc: true
    number-sections: true
    number-depth: 3
    default-image-extension: tif
  pdf:
    documentclass: scrbook
    default-image-extension: pdf
    classoption:
     - headsepline=true
     - open=any
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
     \usepackage{xcolor}
     \usepackage{float}
     \floatplacement{figure}{H}
     \raggedbottom
     \usepackage[automark]{scrlayer-scrpage}
     \clearpairofpagestyles
     
     \lofoot*{\vspace{20mm} \\ \pagemark}
     \refoot*{\vspace{20mm} \\ \pagemark}
     
     \chead{\headmark}
     \addtokomafont{pagehead}{\bfseries\upshape\color{white}}
     \addtokomafont{pagenumber}{\bfseries\color{blue!40!black}}
     % shift the predefined head layers
     \ForEachLayerOfPageStyle*{scrheadings}{%
     \ifstrstart{#1}{scrheadings.head.}
     {\ModifyLayer[addvoffset=-.5in-.5\voffset-.5\topmargin]{#1}}
     {}%
     }
     \ForEachLayerOfPageStyle*{plain.scrheadings}{%
     \ifstrstart{#1}{plain.scrheadings.head.}
     {\ModifyLayer[addvoffset=-.5in-.5\voffset-.5\topmargin]{#1}}
     {}%
     }
     % Defining the Layer
     \DeclareLayer[
     background,
     topmargin,
     addheight=\headheight,
     contents={%
        \color{blue!40!black}%
        \rule{\layerwidth}{\layerheight}%
     }%
     ]{my.head.background}
     %Adding the Layer to the pagestyles
     \AddLayersAtBeginOfPageStyle{scrheadings}{my.head.background}
     \AddLayersAtBeginOfPageStyle{plain.scrheadings}{my.head.background}
      
      \usepackage{tocbibind}
      \usepackage{titling}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \large
        \lineskip 0.5em%
        (WORK-IN-PROGRESS DRAFT OF!) PhD dissertation\\
        \vspace{25mm}
      }
      \postauthor{
        \end{center}
      }
      \predate{
        \begin{center}
        \vspace*{\fill}
        Faculty of Health\\        % Degree stream
        Aarhus University\\                       % University
      }
      \postdate{
        \\
        \resizebox{.9\textwidth}{!}{%
        \includegraphics[width=7in]{figures/au_health.png}%
        \quad
        \includegraphics[width=1in]{figures/static_qr.png}%
        }
        \end{center}
        
        
       }



