# Supplementary validation analyses {#sec-nhs-validation}

### Validation of unspecified diabetes in the Health In Central Denmark survey and in the National Health Survey.

Validation analyses performed in the HICD study population from study I:

::: {#tbl-sup-dm-hicd layout-ncol="1"}
| **OSDC**        | **Survey: +DM**      | **Survey: -DM** | **Total N** |
|-----------------|----------------------|-----------------|-------------|
| **OSDC: +DM**   | 2,512                | 221             | 2,733       |
| **OSDC: -DM**   | 121                  | 26,537          | 26,658      |
| **Total N**     | 2,633                | 26,758          | 29,391      |
| **Sensitivity** | 0.954 (0.945, 0.962) |                 |             |
| **Specificity** | 0.992 (0.991, 0.993) |                 |             |
| **PPV**         | 0.919 (0.908, 0.929) |                 |             |
| **NPV**         | 0.995 (0.995, 0.996) |                 |             |

: The Open-Source Diabetes Classifier (OSDC)

| **RSCD**        | **Survey: +DM**      | **Survey: -DM** | **Total N** |
|-----------------|----------------------|-----------------|-------------|
| **RSCD: +DM**   | 2,422                | 122             | 2,544       |
| **RSCD: -DM**   | 211                  | 26,636          | 26,847      |
| **Total N**     | 2,633                | 26,758          | 29,391      |
| **Sensitivity** | 0.920 (0.909, 0.930) |                 |             |
| **Specificity** | 0.995 (0.995, 0.996) |                 |             |
| **PPV**         | 0.952 (0.943, 0.960) |                 |             |
| **NPV**         | 0.992 (0.991, 0.993) |                 |             |

: The Register for Selected Chronic Diseases (RSCD)

**Supplementary: Validation of uspecified diabetes in the HICD study population**
:::

Validation analyses performed among respondents in the National Health Survey 2017 (individuals reporting diabetes as a current disease were considered diabetes cases).

::: {#tbl-sup-dm-nhs layout-ncol="1"}
| **OSDC**        | **Survey: +DM**   | **Survey: -DM** | **Total N** |
|-----------------|-------------------|-----------------|-------------|
| **OSDC: +DM**   | 1,630             | 258             | 1,888       |
| **OSDC: -DM**   | 87                | 26,46           | 26,547      |
| **Total N**     | 1,717             | 26,718          | 28,435      |
| **Sensitivity** | 0.95 (0.94, 0.96) |                 |             |
| **Specificity** | 0.99 (0.99, 0.99) |                 |             |
| **PPV**         | 0.86 (0.85, 0.88) |                 |             |
| **NPV**         | 1.00 (1.00, 1.00) |                 |             |

: The Open-Source Diabetes Classifier (OSDC)

| **RSCD**        | **Survey: +DM**   | **Survey: -DM** | **Total N** |
|-----------------|-------------------|-----------------|-------------|
| **RSCD: +DM**   | 1,546             | 184             | 1,730       |
| **RSCD: -DM**   | 171               | 26,534          | 26,705      |
| **Total N**     | 1,717             | 26,718          | 28,435      |
| **Sensitivity** | 0.90 (0.89, 0.91) |                 |             |
| **Specificity** | 0.99 (0.99, 0.99) |                 |             |
| **PPV**         | 0.89 (0.88, 0.91) |                 |             |
| **NPV**         | 0.99 (0.99, 0.99) |                 |             |

: The Register for Selected Chronic Diseases (RSCD)

**Supplementary: Validation of uspecified diabetes in the National Health Survey**
:::

::: {.content-visible when-format="pdf"}
# Full papers {#sec-papers}

## Paper I

\newpage

## Paper II

\newpage

## Paper III
:::

::: {.content-visible when-format="html"}
# Addenda and errata

This chapter contains an overview of:

-   Addenda: contents added since the submitted version of the disseration ([commit db88939](https://github.com/Aastedet/dissertation/commit/db889394f613a8e0b034904f97a75e2d4e09da9c)).
-   Errate: corrections to errors discovered since submission of the dissertation.

Naturally, this chapter is only present if the website version.

## Addenda

## Errata

-   In section 5.1.5. Incidence and demographic characteristics of register-based diabetes cohorts, the following excerpt on the interpretation of @fig-age-inclusion-by-year states:
    -   "Before 2016, when HbA1c data was not available from all regions of Denmark, a spike of inclusions is seen for women with T2D included at age 40 years. This spike is absent in the subsequent years, but the distribution is slightly skewed with a plateau in the age range 40-45 years. This is likely a residual effect of women in this age range having been prematurely included in the preceding years."

        -   This statement misinterprets some elements of the figure, addressed below:

            -   The density plots are smoothed, which smoothes out spikes in single years compared to a histogram of observed counts (due to statistical disclosure requirements, this data could not be visualised using histograms). While the spike in included OSDC T2D-cases among women age 40 is indeed much lower in the years 2016-2018 than in the previous years, it is still present.

            -   The spike is likely to be caused by women from Southern Denmark Region (which did not supply complete HbA1c data before 2016) with onset of T2D before the age of 40 years during calendar years before 2016. These women may have initiated metformin treatment before 2016. If they achieved stable euglycaemia using only metformin, they would not be be captured by the HbA1c inclusion criterion, and their inclusion into the cohort would be delayed until censoring of metformin purchases ceases at age 40 years.
:::
