# Addenda and errata

This chapter contains an overview of:

-   Addenda: contents added since the submitted version of the disseration ([commit db88939](https://github.com/Aastedet/dissertation/commit/db889394f613a8e0b034904f97a75e2d4e09da9c)).
-   Errata: corrections to errors discovered since submission of the dissertation.

## Addenda

- 5 May 2023:
    - Study I paper published. List of studies updated with citation and link to doi.
- 8 August 2023:
    - Study III paper published. List of studies updated with citation and link to doi.

## Errata

-   2 May 2023:
    -   On lines 5-10, page 81, section 5.1.5., the following excerpt on the interpretation of @fig-age-inclusion-by-year states:

    -   "Before 2016, when HbA1c data was not available from all regions of Denmark, a spike of inclusions is seen for women with T2D included at age 40 years. This spike is absent in the subsequent years, but the distribution is slightly skewed with a plateau in the age range 40-45 years. This is likely a residual effect of women in this age range having been prematurely included in the preceding years."

        -   This statement misinterprets some elements of the figure, which are addressed below:

        -   The density plots are smoothed, and spikes in single years are less visible compared to a histogram of observed counts (due to statistical disclosure requirements, this data could not be visualised using histograms). While the spike in included OSDC T2D-cases among women age 40 is indeed much lower in the years 2016-2018 than in the previous years, it is still present.

        -   Most likely, the spike is caused by women with onset of T2D before the age of 40 years during a period of time without HbA1c data. These women may have initiated metformin treatment before HbA1c data became available, and if they achieved stable euglycaemia using only metformin, they would not be be captured by the HbA1c inclusion criterion after the HbA1c data became available. Thus, their inclusion into the cohort would be delayed until the censoring of metformin purchases ceases at age 40 years, causing a spike at this age of inclusion. In the post-2016 data, women living in the Southern Denmark Region (which did not supply HbA1c data prior to 2015, compared to the other regions, which supplied data from 2011 onwards) are likely the major source of this spike.
