# Appendix B {#sec-supplementary-material}

## Supplementary material

### Study I

#### Coding scheme

Link to blob

#### Supplementary analyses

Link to blob

### Study II

#### Coding scheme

Link to blob

#### Supplementary analyses

Link to blob

### Study III

#### Coding scheme

Link to blob

#### Supplementary analyses

Link to blob

## To do/Questions:

-   Revisit the prefacing section of each chapter after revisions
-   Consider revising classifierdiffs figures for improve legibility/nationwide counts.
-   Translate/revise figures from DST
-   Tilføj NHS analyser fra methods selection bias discussion i (separat?) supplementary?
-   Statistical analyses section describes only main analyses. Should a summary of supplementary/sensitivity analyses be included (elsewhere?)?
-   Clean up references (introduction and discussion in particular)

### Introduction:

#### Clinical guidelines:

*Social ulighed: Beskriv evt. kort begreb og relation/forskelle ift. projektet. Henvis til supplementary analyser i results?*

Fig. 1.3: Indvandringsår: Skal den med, og hvor meget skal der skrives for at redde den.

### Methods

Table: Overview of 3 studies

### Discussion

Diskutér det forskellige fokus fra studie 2 til 3: Guideline-anbefalinger er mere absolutte, derfor primært fokus på ujusterede estimater i studie II. Der er ikke sort-hvide mål for kombinationsbehandling/præparatvalg, så behandlingen hviler på et samlet klinisk billede, hvorfor det primære fokus på justerede estimater i studie III.

Migrants: Some of the risks in migrants are due to other clinical and socioeconomic risk factors that are more prevalent in migrants compared to native Danes. These risk factors are not the focus of this dissertation and are not presented in the main results. However, these risk factors are of key importance in a greater scope of equity in T2D care provision, and readers are urged to explore the online appendix, where they are presented. The following section provides a brief summary of overall patterns found among covariates of analyses:

BLOB:

Kap 5.1.2: PCOS:

The age-based censoring constituted the vast majority of censored events, as data on indication codes was available in only a minority of prescriptions (contrary to the 72% of all prescriptions described by official documentation).\[\@lmdbdoc\]

The following section provides a brief summary of overall patterns found among covariates of analyses:

First, we found that register-based classifiers identified valid populations of T1D and T2D in a general population, although diabetes type in cases with atypical age at onset of diabetes should be interpreted with caution. Next, we found that overall T2D care in Denmark had considerable room for improvement, and we identified areas of care where migrants were at increased risk of not receiving guideline-level care compared to native Danes. Disparities between migrants and native Danes were most common in aspects of diabetes monitoring and control of HbA1c and LDL-C levels, while no overall pattern of disparity was observed for absence of pharmacological treatment in individuals with an indication for treatment. Finally, we found that most migrant groups were less likely to receive GLD combination therapy, and that migrants were more likely to use oral GLDs, but much less likely to use injection-based GLDs -- particularly GLP1RAs.

Migrants from Somalia stood out in particular, as they had cross all aspects of care, : worst. Esp. dyslipidemia.

Some of the risks in migrants are due to other clinical and socioeconomic risk factors that are more prevalent in migrants compared to native Danes. These

Disparities between migrant groups and native Danes, yes, but much can be attributed to differences in clinical characteristics. Largest disparities in podiatrist monitoring, control of HbA1c and LDL-cholesterol and GLP1RA use. Migrants from Somalia received "poorer" care in all outcomes, and poorest care of all groups in most.

In study II, the main focus was on the unadjusted estimates, as most of the guideline recommendations apply more or less equally to all individuals with T2D, regardless of other characteristics. In study III the focus is on the fully-adjusted estimates, as the indication for combination therapy and individual GLD types depends on the characteristics of the individual patient.

## Discussion / implications

Kap 6: Hvad foregår der i ude i klinikken

-   kan essensen af nuværende implikations-afsnit indgå i diskussionen. Evt. som separat underkapitel 6.x: clinical considerations, explanations, implications

Kap 7: indeholder typisk mere konklusioner på baggrund af det diskuterede

evt. slette implikations-kapitel (men så tilføje et par sætninger før/efter main konklusions) - perspektives indeholder ofte ca. det samme indhold som implikations (som er unødvendig).
