# Supervisors and assessment committee {.unnumbered}

#### PhD student:

**Anders Aasted Isaksen, MD**\
Department of Public Health, Aarhus University, Denmark

#### Supervisors:

**Professor Annelli Sandbæk, PhD (main supervisor)**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Denmark

**Associate Professor Mette Vinther Skriver, PhD**\
Department of Public Health, Aarhus University, Denmark

**Lasse Bjerg, PhD**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Denmark

#### Assessment committee:

**Professor Reimar Wernich Thomsen, PhD (chairman)**\
Department of Clinical Epidemiology, Department of Clinical Medicine, Aarhus University Hospital, Denmark

**Professor Per Wändell, PhD**\
Division of Family Medicine and Primary Care, Department of Neurobiology, Care Sciences and Society, Karolinska Institutet

**Senior researcher Nana Folmann Hempler, PhD**\
Diabetes Management Research, Steno Diabetes Center Copenhagen, Denmark
