# English summary {#sec-english .unnumbered}

**Background**: Type 2 diabetes (T2D) is an increasing burden on healthcare services due to changes in demography and lifestyle. Migrants are particularly vulnerable to T2D, having a higher prevalence of the disease compared to native populations in western Europe, with some evidence suggesting a higher risk of complications and mortality. Evidence on disparities in care that may contribute to this excess risk in migrants is sparse, but register-based studies are well-suited to explore this in a Danish context. However, these studies are vulnerable to biases due to the lack of a validated method to identify T2D cases in the general population.

**Aims**: This dissertation aimed to develop and validate a register-based classification of type 1 diabetes (T1D) and T2D, and utilise it to explore specific areas of monitoring, biomarker levels, and pharmacological treatment, where disparities in T2D care between migrant groups and native Danes may contribute to excess complication risk in migrants.

**Methods**: Three cross-sectional register-based studies were performed. Study I validated two register-based classifications of diabetes - the *Open-Source Diabetes Classifier* (OSDC), and the *Register of Selected Chronic Diseases* (RSCD) - in a population of survey respondents from Central Denmark Region (*Health In Central Denmark*), while the two subsequent studies examined T2D prevalence and care in nationwide populations, using native Danes as the reference group. Study II computed relative risk (RR) of prevalent T2D and non-fulfilment of eleven indicators corresponding to guideline-recommendations. Study III computed RR of using glucose-lowering drug (GLD) combination therapy, and RR of using each type of GLD.

**Results**: In study I, both register-based diabetes classifiers identified valid populations of T1D and T2D in a general population (positive predictive values from 87.5% to 94.4%, negative predictive values above 98.9%), although sensitivity in the OSDC was substantially higher compared to the RSCD in both T1D (77.3% vs. 70.0%) and in T2D (94.4% vs. 90.5%). Neither algorithm was able to accurately classify diabetes type in individuals with T1D onset after age 40, nor T2D onset before age 40. In study II, prevalence of T2D was higher in all migrants excluding the Europe-group (fully-adjusted RR from 0.96 \[95% confidence interval: 0.94-0.99\] (Europe-group) to 4.04 \[3.89-4.20\] (Sri Lanka-group)). Non-fulfilment of recommendations for care was common - regardless of origin: in eight of the eleven indicators of care studied \>25% of native Danes did not meet guideline-recommendations. Apart from monitoring in the Sri Lanka-group, migrants were at similar or higher risk of non-fulfilment than native Danes across all indicators of monitoring (crude RR from 0.64 \[0.51-0.80\] (hemoglobin-A1c (HbA1c) monitoring, Sri Lanka-group) to 1.62 \[1.36-1.95\] (HbA1c monitoring, Somalia)), HbA1c control (crude RR from 1.27 \[1.24-1.30\] (Middle East-group) to 1.46 \[1.41-1.52\] (Pakistan-group)), and low-density lipoprotein cholesterol (LDL-C) control (crude RR from 1.08 \[1.03-1.14\] (Former Yugoslavia-group) to 1.78 \[1.67-1.90\] (Somalia-group)), while no overall disparities were observed for the presence of pharmacological treatment (crude RR from 0.61 \[0.46-0.80\] (GLD, Sri Lanka-group) to 1.67 \[1.34-2.09\] (GLD, Somalia-group)). In study III, migrants were less likely to use GLD combination therapy than native Danes (fully-adjusted RR from 0.77 \[0.71-0.85\] (Somalia-group) to 1.00 \[0.97-1.04\] (Former Yugoslavia-group)). Migrants were more likely to use oral GLD types (fully-adjusted RR (use of any oral GLD) from 0.99 \[0.97-1.01\] (Europe-group) to 1.09 \[1.06-1.11\] (Sri Lanka-group)), but less likely to use injection-based GLD types such as insulins (fully-adjusted RR from 0.66 \[0.62-0.71\] (Sri Lanka-group) to 0.94 \[0.89-0.99\] (Europe-group)) and, especially, glucagon-like peptide-1 receptor agonists (GLP1RA) (fully-adjusted RR from 0.29 \[0.22-0.39\] (Somalia-group) to 0.95 \[0.89-1.01\] (Europe-group)).

**Conclusion and perspectives** This dissertation was able to accurately identify populations of T1D and T2D in register data from the general Danish population. Diabetes epidemiologists can rely on the OSDC and the RSCD to provide valid study populations for Danish register-based research, but researchers should be aware of limitations in cases with atypical age at onset and potential challenges due to evolving GLD indications in the future. This dissertation found room for improvement in T2D care in Denmark, and presented several disparities in T2D care between migrants and native Danes. These may contribute excess risk of complication and mortality in migrants, especially among migrants from Somalia, who received the poorest care of all groups overall. Overall, the large disparity in use of GLP1RA between migrants and native Danes may provide a target for future interventions to improve care and reduce complication risk among migrants with T2D.
