# Dansk resumé {#sec-danish .unnumbered}

**Baggrund**: Type 2 diabetes (T2D) er en stigende belastning på sundhedsvæsenet på grund af ændringer i demografi og livsstil. Indvandrere er særligt sårbare overfor T2D, idet de har en højere forekomst af sygdommen i forhold til indfødte befolkninger i Vesteuropa, ligesom nogle undersøgelser peger på en højere risiko for diabetiske komplikationer og død. Potentielle uligheder i behandlingen, der kan bidrage til den øgede risiko hos indvandrere med T2D, er dårligt belyst, men registerbaserede studier er velegnede til at undersøge dette i en dansk sammenhæng. Disse undersøgelser er imidlertid sårbare, idet der ikke foreligger nogen validerede metoder til at identificere T2D-tilfælde i den generelle danske befolkning.

**Formål**: Denne afhandling havde til formål at udvikle og validere en registerbaseret klassifikation af type 1 diabetes (T1D) og T2D, og anvende den til at undersøge specifikke områder i behandlingen af T2D - kontroller, biomarkør-niveauer og medicinsk behandling - hvor uligheder mellem indvandrergrupper og indfødte danskere kan bidrage til øget risiko for komplikationer hos indvandrere.

**Metoder**: Som led i afhandlingen blev tre tværsnitsstudier baseret på register-data gennemført. Studie I validerede to registerbaserede klassifikationer af diabetes - *Open-Source Diabetes Classifier* (OSDC) og *Register for Udvalgte Kroniske Sygdomme* (RUKS) - blandt spørgeskema-besvarelser fra personer i Region Midtjylland (*Helbred i Midt*), mens de to efterfølgende studier undersøgte forekomst og behandling af T2D i hele landet og sammenlignede indvandrergrupper med indfødte danskere. Studie II beregnede relativ risiko (RR) for forekomst af T2D og for manglende opfyldelse af elleve indikatorer for behandlingskvalitet svarende til anbefalinger i gældende kliniske retningslinjer. Studie III beregnede RR for brug af kombinationsbehandling med blodsukker-nedsættende lægemidler (GLD) og RR for brug af hver type GLD.

**Resultater**: I studie I identificerede begge registerbaserede diabetesklassifikationer gyldige populationer af T1D og T2D i en bred befolkning (positive prædiktive værdier fra 87,5% til 94,4%, negative prædiktive værdier over 98,9%), dog med en væsentlig højere sensitivitet i OSDC sammenlignet med RUKS både i T1D (77,3% vs. 70,0%) og i T2D (94,4% vs. 90,5%). Ingen af algoritmerne var i stand til nøjagtigt at klassificere diabetestype hos personer med T1D debut efter 40-årsalderen eller T2D debut før 40-årsalderen. I studie II var forekomsten af T2D højere i alle indvandrergrupper undtagen Europa-gruppen (fuldt justeret RR fra 0,96 \[95% konfidensinterval: 0,94-0,99\] (Europa-gruppen) til 4,04 \[3,89-4,20\] (Sri Lanka-gruppen)). Manglende opfyldelse af de vejledende behandlingsanbefalinger var hyppig - uanset oprindelse: i otte ud af elleve indikatorer opfyldte \>25% af indfødte danskere ikke anbefalingerne. Fraset rutinemæssig kontrolundersøgelser i Sri Lanka-gruppen, havde indvandrergrupperne tilsvarende eller højere risiko end indfødte danskere for ikke at opfylde behandlingsanbefalinger på tværs af alle indikatorer for rutinemæssig kontrolundersøgelser (rå RR fra 0,64 \[0,51-0,80\] (hæmoglobin-A1c (HbA1c-undersøgelse, Sri Lanka-gruppen) til 1,62 \[1,36-1,95\] (HbA1c-undersøgelse, Somalia-gruppen)), blodsukkerniveau (rå RR fra 1,27 \[1,24-1,30\] (Mellemøsten-gruppen) til 1,46 \[1,41-1,52\] (Pakistan-gruppen)) og kolesterolniveau (rå RR fra 1,08 \[1,03-1,14\] (Eksjugoslavien-gruppen) til 1,78 \[1,67-1,90\] (Somalia-gruppen)), mens der ikke sås nogen gennemgående forskelle for tilstedeværelse af medicinsk behandling (rå RR fra 0,61 \[0,46-0,80\] (GLD, Sri Lanka-gruppen) til 1,67 \[1,34-2,09\] (GLD, Somalia-gruppen)). I studie III var indvandrere mindre tilbøjelige til at få GLD kombinationsbehandling end indfødte danskere (fuldt justeret RR fra 0,77 \[0,71-0,85\] (Somalia-gruppen) til 1,00 \[0,97-1,04\] (Eksjugoslavien-gruppen)). Indvandrere var mere tilbøjelige til at benytte orale GLD typer (fuldt justeret RR (brug af ethvert oralt GLD) fra 0,99 \[0,97-1,01\] (Europa-gruppen) til 1,09 \[1,06-1,11\] (Sri Lanka-gruppen)), men mindre tilbøjelige til at benytte injektionsbaserede GLD typer så som insuliner (fuldt justeret RR fra 0,66 \[0,62-0,71\] (Sri Lanka-gruppen) til 0,94 \[0,89-0,99\] (Europa-gruppen)) og især glucagon-like peptide-1 receptor agonister (GLP1RA) (fuldt justeret RR fra 0,29 \[0,22-0,39\] (Somalia-gruppen) til 0,95 \[0,89-1,01\] (Europa-gruppen)).

**Konklusion og perspektiver**: Denne ph.d.-afhandling kunne præcist identificere befolkninger med T1D og T2D i den brede danske befolkning ud fra registerdata. Diabetesforskere kan anvende OSDC og RUKS til at danne gyldige studiepopulationer ud fra de danske registre, men bør være opmærksomme på deres begrænsninger, herunder blandt patienter med atypisk alder for sygdomsdebut samt potentielle udfordringer som følge af udviklingen i brugen af GLD i fremtiden. Afhandlingen fandt plads til forbedringer i behandlingen af T2D i Danmark, og viste flere uligheder mellem indvandrere og indfødte danskere i behandlingen af T2D, som kan medføre øget risiko for komplikationer og død blandt indvandrere - særligt blandt indvandrere fra Somalia, som havde den laveste behandlingskvalitet af alle grupper. Den store forskel i brugen af GLP1RA mellem indvandrere og indfødte danskere kan muligvis være et mål for fremtidige interventioner til at øge behandlingskvaliteten og mindske komplikationsrisikoen blandt indvandrere med T2D.
